title: Sibi Lawrence
description: Azure Cloud, Infrastructure Engineering, Automation and SRE

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Sibi Lawrence"
  
